[package]
name = "whatshouldwewatch"
version = "0.1.0"
edition = "2021"

[dependencies]
json = "0.12.4"
reqwest = "0.12.12"
serde = { version = "1.0.218", features = ["derive", "serde_derive"] }
tokio = { version = "1.44.0", features = ["full"] }
